version: 1

handlers:
  match:
    package_names:
      - transport
  signature:
    require_context_first_arg: true
    require_pointer_request: true
    require_pointer_response: true
    require_error_return: true

layers:
  - name: application
    match:
      call_name_contains:
        - application
        - processor
      receiver_type_contains:
        - Application
        - Processor

  - name: domain
    match:
      receiver_type_contains:
        - Policy

  - name: persistence
    match:
      receiver_type_contains:
        - Store

  - name: external_client
    match:
      receiver_type_contains:
        - Client

ignore:
  standard_library: true
  getters:
    local_values: true
    receiver_names:
      - req

resolution:
  skip_implementations:
    receiver_name_prefixes:
      - Mock
      - Fake
